/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author solit
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        master = new javax.swing.JMenu();
        siswa = new javax.swing.JMenuItem();
        guru = new javax.swing.JMenuItem();
        kelas = new javax.swing.JMenuItem();
        mata_pelajaran = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        transaksi_nilai = new javax.swing.JMenuItem();
        presentasi = new javax.swing.JMenuItem();
        report = new javax.swing.JMenu();
        siswa_report = new javax.swing.JMenuItem();
        guru_report = new javax.swing.JMenuItem();
        kelas_report = new javax.swing.JMenuItem();
        nilai = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem10.setText("jMenuItem10");

        jMenuItem13.setText("jMenuItem13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/school_students_icon_144607 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jMenuBar2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        master.setText("Master");

        siswa.setText("Siswa");
        siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siswaActionPerformed(evt);
            }
        });
        master.add(siswa);

        guru.setText("Guru");
        guru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guruActionPerformed(evt);
            }
        });
        master.add(guru);

        kelas.setText("Kelas");
        kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasActionPerformed(evt);
            }
        });
        master.add(kelas);

        mata_pelajaran.setText("Mata Pelajaran");
        mata_pelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mata_pelajaranActionPerformed(evt);
            }
        });
        master.add(mata_pelajaran);

        jMenuBar2.add(master);

        transaksi.setBackground(new java.awt.Color(255, 153, 153));
        transaksi.setText("Transaksi");

        transaksi_nilai.setText("Transaksi NIlai");
        transaksi_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksi_nilaiActionPerformed(evt);
            }
        });
        transaksi.add(transaksi_nilai);

        presentasi.setText("Presentasi");
        transaksi.add(presentasi);

        jMenuBar2.add(transaksi);

        report.setText("Report");

        siswa_report.setText("Siswa");
        report.add(siswa_report);

        guru_report.setText("Guru");
        report.add(guru_report);

        kelas_report.setText("Kelas");
        kelas_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelas_reportActionPerformed(evt);
            }
        });
        report.add(kelas_report);

        nilai.setText("NIlai");
        report.add(nilai);

        jMenuBar2.add(report);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siswaActionPerformed
        new siswa().setVisible(true);
        
    }//GEN-LAST:event_siswaActionPerformed

    private void transaksi_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksi_nilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transaksi_nilaiActionPerformed

    private void kelas_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelas_reportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelas_reportActionPerformed

    private void mata_pelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mata_pelajaranActionPerformed
        new mata_pelajaran ().setVisible(true);
    }//GEN-LAST:event_mata_pelajaranActionPerformed

    private void guruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guruActionPerformed
        new guru().setVisible(true);

    }//GEN-LAST:event_guruActionPerformed

    private void kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasActionPerformed
        new kelas().setVisible(true);
    }//GEN-LAST:event_kelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem guru;
    private javax.swing.JMenuItem guru_report;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenuItem kelas;
    private javax.swing.JMenuItem kelas_report;
    private javax.swing.JMenu master;
    private javax.swing.JMenuItem mata_pelajaran;
    private javax.swing.JMenuItem nilai;
    private javax.swing.JMenuItem presentasi;
    private javax.swing.JMenu report;
    private javax.swing.JMenuItem siswa;
    private javax.swing.JMenuItem siswa_report;
    private javax.swing.JMenu transaksi;
    private javax.swing.JMenuItem transaksi_nilai;
    // End of variables declaration//GEN-END:variables
}
